#include <stdint.h>

typedef struct {
    uint16_t JumpCode2;
    uint16_t FaultHistory1;
    uint16_t FaultHistory2;
    uint16_t FaultHistory3;
    uint16_t FaultHistory4;
    uint16_t FaultHistory5;
    uint16_t ResetFaultHistory;
    uint16_t DwellFrequency;
    uint16_t DwellTime;
    uint16_t SkipFrequencySelect;
    uint16_t SkipFrequencyLowLimit1;
    uint16_t SkipFrequencyHiLimit1;
    uint16_t SkipFrequencyLowLimit2;
    uint16_t SkipFrequencyHiLimit2;
    uint16_t SkipFrequencyLowLimit3;
    uint16_t SkipFrequencyHiLimit3;
    uint16_t SCurveAccelDecelStartSide;
    uint16_t SCurveAccelDecelEndSide;
    uint16_t IOPhaseLoseProtectionSelect;
    uint16_t PowerOnStartSelect;
    uint16_t RestartAfterFaltResetSelection;
    uint16_t SpeedSearchSelect;
    uint16_t CurrentLevelDuringSpeedSreach;
    uint16_t PGainDuringSpeedSreach;
    uint16_t IGainDuringSpeedSreach;
    uint16_t NumberOfAutoRestartTry;
    uint16_t AutoRestartTime;
    uint16_t MotorTypeSelect;
    uint16_t NumbersOfMotorPoles;
    uint16_t RatedSlipFrequency;
    uint16_t MotorRatedCurrent;
    uint16_t NoLoadMotorCurrent;
    uint16_t MotorEfficiency;
    uint16_t LoadInteriaRate;
    uint16_t CarrierFrequencySelect;
    uint16_t ControlModeSelect;
    uint16_t AutoTuning;
    uint16_t StatorResistance;
    uint16_t LeakageInductance;
    uint16_t SensorlessPGain;
    uint16_t SensorlessIGain;
    uint16_t SensorlessTorqueLimit;
    uint16_t PWMModeSelect;
    uint16_t PIDSelect;
    uint16_t PIDFBSelect;
    uint16_t PGainForPID;
    uint16_t IntegralTimeForPID;
    uint16_t DifferentialTimeForPID;
    uint16_t PIDModeControlSelect;
    uint16_t PIDOutputFrequencyHighLimit;
    uint16_t PIDOutputFrequencyLowLimit;
    uint16_t PIDStandardValueSelect;
    uint16_t PIDControlUnitSelect;
    uint16_t PIDOutputInverse;
    uint16_t SelfDiagnosticSelect;
    uint16_t SleepDelayTime;
    uint16_t SleepFrequency;
    uint16_t WakeUplevel;
    uint16_t KEBDriveSelect;
    uint16_t KEBActionStartLevel;
    uint16_t KEBActionStopLevel;
    uint16_t KEBActionGain;
    uint16_t FrequencyReferenceForAccelDecel;
    uint16_t AccelDecelTimeScale;
    uint16_t PowerOnDisplay;
    uint16_t MonitoringItemSelect;
    uint16_t GainForMotorRPMDisplay;
    uint16_t DBResistorOperatingRateLimitSel;
    uint16_t DBResistorOperatingRate;
    uint16_t CoolingFanControl;
    uint16_t OperatingMethodFanMalfunctions;
    uint16_t SWVersion;
    uint16_t SecondMotorAccelTime;
    uint16_t SecondMotorDecelTime;
    uint16_t SecondMotorBaseBaseFrequency;
    uint16_t SecondMotorVFPattern;
    uint16_t SecondMotorForwardTorqueBoost;
    uint16_t SecondMotorReverseTorqueBoost;
    uint16_t SecondMotorSttallPreventionLevel;
    uint16_t SecondMotorElThermalLvlFor1Minute;
    uint16_t SecondMotorElThermalLvlForConti;
    uint16_t SecondMotorRatedCurrnet;
    uint16_t ParameterRead;
    uint16_t ParameterWrite;
    uint16_t ParameterInitialize;
    uint16_t PasswordRegister;
    uint16_t ParameterLock;
}F2_t;

//Memory allocation
F2_t* F2_new()
{
    return (F2_t*)malloc(sizeof(F2_t));
}

void F2_ctor(F2_t* F2)
{
    F2->JumpCode2 = 0xA300;
    F2->FaultHistory1 = 0xA301;
    F2->FaultHistory2 = 0xA302;
    F2->FaultHistory3 = 0xA303;
    F2->FaultHistory4 = 0xA304;
    F2->FaultHistory5 = 0xA305;
    F2->ResetFaultHistory = 0xA306;
    F2->DwellFrequency = 0xA307;
    F2->DwellTime = 0xA308;
    F2->SkipFrequencySelect = 0xA30A;
    F2->SkipFrequencyLowLimit1 = 0xA30B;
    F2->SkipFrequencyHiLimit1 = 0xA30C;
    F2->SkipFrequencyLowLimit2 = 0xA30D;
    F2->SkipFrequencyHiLimit2 = 0xA30E;
    F2->SkipFrequencyLowLimit3 = 0xA30F;
    F2->SkipFrequencyHiLimit3 = 0xA310;
    F2->SCurveAccelDecelStartSide = 0xA311;
    F2->SCurveAccelDecelEndSide = 0xA312;
    F2->IOPhaseLoseProtectionSelect = 0xA313;
    F2->PowerOnStartSelect = 0xA314;
    F2->RestartAfterFaltResetSelection = 0xA315;
    F2->SpeedSearchSelect = 0xA316;
    F2->CurrentLevelDuringSpeedSreach = 0xA317;
    F2->PGainDuringSpeedSreach = 0xA318;
    F2->IGainDuringSpeedSreach = 0xA319;
    F2->NumberOfAutoRestartTry = 0xA31A;
    F2->AutoRestartTime = 0xA31B;
    F2->MotorTypeSelect = 0xA31E;
    F2->NumbersOfMotorPoles = 0xA31F;
    F2->RatedSlipFrequency = 0xA320;
    F2->MotorRatedCurrent = 0xA321;
    F2->NoLoadMotorCurrent = 0xA322;
    F2->MotorEfficiency = 0xA324;
    F2->LoadInteriaRate = 0xA325;
    F2->CarrierFrequencySelect = 0xA327;
    F2->ControlModeSelect = 0xA328;
    F2->AutoTuning = 0xA329;
    F2->StatorResistance = 0xA32A;
    F2->LeakageInductance = 0xA32C;
    F2->SensorlessPGain = 0xA32D;
    F2->SensorlessIGain = 0xA32E;
    F2->SensorlessTorqueLimit = 0xA32F;
    F2->PWMModeSelect = 0xA330;
    F2->PIDSelect = 0xA331;
    F2->PIDFBSelect = 0xA332;
    F2->PGainForPID = 0xA333;
    F2->IntegralTimeForPID = 0xA334;
    F2->DifferentialTimeForPID = 0xA335;
    F2->PIDModeControlSelect = 0xA336;
    F2->PIDOutputFrequencyHighLimit = 0xA337;
    F2->PIDOutputFrequencyLowLimit = 0xA338;
    F2->PIDStandardValueSelect = 0xA339;
    F2->PIDControlUnitSelect = 0xA33A;
    F2->PIDOutputInverse = 0xA33B;
    F2->SelfDiagnosticSelect = 0xA33C;
    F2->SleepDelayTime = 0xA33D;
    F2->SleepFrequency = 0xA33E;
    F2->WakeUplevel = 0xA33F;
    F2->KEBDriveSelect = 0xA340;
    F2->KEBActionStartLevel = 0xA341;
    F2->KEBActionStopLevel = 0xA342;
    F2->KEBActionGain = 0xA343;
    F2->FrequencyReferenceForAccelDecel = 0xA346;
    F2->AccelDecelTimeScale = 0xA347;
    F2->PowerOnDisplay = 0xA348;
    F2->MonitoringItemSelect = 0xA349;
    F2->GainForMotorRPMDisplay = 0xA34A;
    F2->DBResistorOperatingRateLimitSel = 0xA34B;
    F2->DBResistorOperatingRate = 0xA34C;
    F2->CoolingFanControl = 0xA34D;
    F2->OperatingMethodFanMalfunctions = 0xA34E;
    F2->SWVersion = 0xA34F;
    F2->SecondMotorAccelTime = 0xA351;
    F2->SecondMotorDecelTime = 0xA352;
    F2->SecondMotorBaseBaseFrequency = 0xA353;
    F2->SecondMotorVFPattern = 0xA354;
    F2->SecondMotorForwardTorqueBoost = 0xA355;
    F2->SecondMotorReverseTorqueBoost = 0xA356;
    F2->SecondMotorSttallPreventionLevel = 0xA357;
    F2->SecondMotorElThermalLvlFor1Minute = 0xA358;
    F2->SecondMotorElThermalLvlForConti = 0xA359;
    F2->SecondMotorRatedCurrnet = 0xA35A;
    F2->ParameterRead = 0xA35B;
    F2->ParameterWrite = 0xA35C;
    F2->ParameterInitialize = 0xA35D;
    F2->PasswordRegister = 0xA35E;
    F2->ParameterLock = 0xA35F;
}

void F2_dtor(F2_t* F2)
{
    //nothing to do
}